# Generated by Django 4.2.1 on 2023-06-14 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser_people', '0002_alter_peoplekeywords_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peoplekeywords',
            name='name',
        ),
    ]
