# Generated by Django 4.2.1 on 2023-06-20 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_people', '0004_alter_peoplekeywords_linkedin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='peopleinfo',
            old_name='birth',
            new_name='connections',
        ),
        migrations.RenameField(
            model_name='peopleinfo',
            old_name='email',
            new_name='education',
        ),
        migrations.RenameField(
            model_name='peopleinfo',
            old_name='twitter',
            new_name='experience',
        ),
        migrations.RenameField(
            model_name='peopleinfo',
            old_name='linkedin',
            new_name='link',
        ),
        migrations.RenameField(
            model_name='peopleinfo',
            old_name='website',
            new_name='skils',
        ),
        migrations.RenameField(
            model_name='peoplekeywords',
            old_name='linkedin',
            new_name='link',
        ),
        migrations.AddField(
            model_name='peopleinfo',
            name='about',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
