# Generated by Django 4.2.2 on 2023-07-07 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser_people', '0005_rename_birth_peopleinfo_connections_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PeopleKeywords',
            new_name='PeopleLinks',
        ),
        migrations.RemoveField(
            model_name='peopleinfo',
            name='status',
        ),
    ]
