# Generated by Django 4.2.2 on 2023-07-07 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_people', '0007_peopleinfo_contact_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peopleinfo',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='peopleinfo',
            name='contact_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='peopleinfo',
            name='education',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='peopleinfo',
            name='experience',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='peopleinfo',
            name='skils',
            field=models.TextField(blank=True, null=True),
        ),
    ]
