# Generated by Django 4.2.1 on 2023-06-13 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompaniesKeywords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('link', models.URLField(max_length=250, unique=True)),
                ('status', models.CharField(default='New', max_length=25)),
            ],
            options={
                'verbose_name': 'LinkCompany',
                'verbose_name_plural': 'LinksCompanies',
            },
        ),
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(max_length=250, unique=True)),
                ('company_website', models.CharField(blank=True, max_length=250, null=True)),
                ('company_name', models.CharField(blank=True, max_length=250, null=True)),
                ('company_size', models.CharField(max_length=250, null=True)),
                ('company_founded', models.CharField(blank=True, max_length=250, null=True)),
                ('company_specialties', models.CharField(blank=True, max_length=250, null=True)),
                ('industry', models.CharField(blank=True, max_length=250, null=True)),
                ('company_headquarters', models.CharField(max_length=250, null=True)),
                ('status', models.CharField(default='New', max_length=25)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
    ]
