# Generated by Django 4.2.1 on 2023-06-13 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser_company', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companieskeywords',
            options={'verbose_name': 'Link', 'verbose_name_plural': 'Links'},
        ),
    ]
