# Generated by Django 4.2.1 on 2023-06-16 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser_company', '0002_alter_companieskeywords_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companieskeywords',
            name='name',
        ),
    ]
