# Generated by Django 4.2.1 on 2023-06-19 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_company', '0003_remove_companieskeywords_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='companieskeywords',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='ipo',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='job_actual',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='learning',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='location',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='nasdaq',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='overview',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='phone',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='programs',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
