# Generated by Django 4.2.1 on 2023-06-20 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser_company', '0004_companieskeywords_name_companyinfo_ipo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companieskeywords',
            old_name='name',
            new_name='company_name',
        ),
    ]
