# Generated by Django 4.2.2 on 2023-07-07 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_company', '0005_rename_name_companieskeywords_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='overview',
            field=models.TextField(null=True),
        ),
    ]
