# Generated by Django 4.2.1 on 2023-06-08 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_job', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacancy', models.CharField(max_length=250, unique=True)),
                ('name_company', models.CharField(max_length=250)),
                ('geo', models.CharField(blank=True, max_length=250, null=True)),
                ('workplacetype', models.CharField(blank=True, max_length=250, null=True)),
                ('schedule', models.CharField(blank=True, max_length=250, null=True)),
                ('about_vacancy', models.CharField(blank=True, max_length=4000, null=True)),
            ],
            options={
                'verbose_name': 'Vacancy',
                'verbose_name_plural': 'Job',
            },
        ),
    ]
