# Generated by Django 4.2.1 on 2023-06-08 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_job', '0002_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='about_vacancy',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='info',
            name='vacancy',
            field=models.CharField(max_length=250),
        ),
    ]
