# Generated by Django 4.2.1 on 2023-06-09 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_job', '0003_alter_info_about_vacancy_alter_info_vacancy'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='about_company',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
