# Generated by Django 4.2.1 on 2023-06-09 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_job', '0004_info_about_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='link',
            field=models.URLField(default='', unique=True),
        ),
        migrations.AddField(
            model_name='info',
            name='status',
            field=models.CharField(default='New', max_length=25),
        ),
        migrations.AlterField(
            model_name='links',
            name='link',
            field=models.URLField(unique=True),
        ),
        migrations.AlterField(
            model_name='links',
            name='status',
            field=models.CharField(default='New', max_length=50),
        ),
    ]
