# Generated by Django 4.2.1 on 2023-06-09 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_job', '0005_info_link_info_status_alter_links_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='link',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='links',
            name='link',
            field=models.URLField(max_length=250, unique=True),
        ),
    ]
