# Generated by Django 4.2.1 on 2023-06-09 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_job', '0006_alter_info_link_alter_links_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompaniesKeywords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('link', models.URLField(max_length=250, unique=True)),
                ('status', models.CharField(default='New', max_length=25)),
            ],
            options={
                'verbose_name': 'Link',
                'verbose_name_plural': 'Links',
            },
        ),
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(max_length=250, unique=True)),
                ('company_website', models.CharField(blank=True, max_length=250, null=True)),
                ('company_name', models.CharField(blank=True, max_length=250, null=True)),
                ('company_size', models.CharField(max_length=250, null=True)),
                ('company_founded', models.CharField(blank=True, max_length=250, null=True)),
                ('company_specialties', models.CharField(blank=True, max_length=250, null=True)),
                ('industry', models.CharField(blank=True, max_length=250, null=True)),
                ('company_headquarters', models.CharField(max_length=250, null=True)),
                ('status', models.CharField(default='New', max_length=25)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Сompanies',
            },
        ),
        migrations.CreateModel(
            name='PeopleInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkedin', models.CharField(max_length=250, unique=True)),
                ('name', models.CharField(max_length=250)),
                ('job', models.CharField(blank=True, max_length=250, null=True)),
                ('geo', models.CharField(blank=True, max_length=250, null=True)),
                ('website', models.CharField(blank=True, max_length=250, null=True)),
                ('birth', models.CharField(blank=True, max_length=250, null=True)),
                ('twitter', models.CharField(blank=True, max_length=250, null=True)),
                ('email', models.CharField(blank=True, max_length=250, null=True)),
                ('status', models.CharField(default='New', max_length=25)),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'People',
            },
        ),
        migrations.CreateModel(
            name='PeopleKeywords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('linkedin', models.URLField(max_length=250, unique=True)),
                ('status', models.CharField(default='New', max_length=25)),
            ],
            options={
                'verbose_name': 'Link',
                'verbose_name_plural': 'Links',
            },
        ),
        migrations.RenameModel(
            old_name='Info',
            new_name='JobInfo',
        ),
        migrations.RenameModel(
            old_name='Links',
            new_name='JobKeywords',
        ),
    ]
