# Generated by Django 4.2.1 on 2023-06-09 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser_job', '0007_companieskeywords_companyinfo_peopleinfo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companieskeywords',
            options={'verbose_name': 'LinkCompany', 'verbose_name_plural': 'LinksCompanies'},
        ),
        migrations.AlterModelOptions(
            name='jobkeywords',
            options={'verbose_name': 'LinkJob', 'verbose_name_plural': 'LinksJob'},
        ),
        migrations.AlterModelOptions(
            name='peoplekeywords',
            options={'verbose_name': 'LinkPeople', 'verbose_name_plural': 'LinksPeople'},
        ),
    ]
