# Generated by Django 4.2.1 on 2023-06-13 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser_job', '0008_alter_companieskeywords_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompaniesKeywords',
        ),
        migrations.DeleteModel(
            name='CompanyInfo',
        ),
        migrations.DeleteModel(
            name='PeopleInfo',
        ),
        migrations.DeleteModel(
            name='PeopleKeywords',
        ),
    ]
