# Generated by Django 4.2.2 on 2023-06-30 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_job', '0010_alter_jobkeywords_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobinfo',
            name='about_company',
        ),
        migrations.RemoveField(
            model_name='jobinfo',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='jobinfo',
            name='workplacetype',
        ),
        migrations.AddField(
            model_name='jobinfo',
            name='employment_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jobinfo',
            name='industries',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jobinfo',
            name='job_functions',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jobinfo',
            name='seniority_level',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jobinfo',
            name='about_vacancy',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobinfo',
            name='geo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jobinfo',
            name='link',
            field=models.CharField(max_length=510, unique=True),
        ),
        migrations.AlterField(
            model_name='jobinfo',
            name='name_company',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jobinfo',
            name='vacancy',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
